# Generated by Django 4.2.8 on 2023-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('expiry_month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('expiry_year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('firstname_surname', models.CharField(max_length=255, verbose_name='Фамилия и Имя')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
            },
        ),
    ]
