# Generated by Django 4.2.8 on 2023-12-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_productimage_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='market.category', verbose_name='Категория'),
        ),
    ]
