# Generated by Django 4.2.8 on 2023-12-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Просмотры'),
        ),
    ]
