# Generated by Django 4.2.8 on 2023-12-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
