# Generated by Django 4.2.8 on 2023-12-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('market_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank_cards',
            field=models.ManyToManyField(blank=True, to='payment.bankcard', verbose_name='Банковская карта'),
        ),
    ]
