# Generated by Django 4.2.8 on 2023-12-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislike',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Дизлайк'),
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Лайк'),
        ),
    ]
