# Generated by Django 4.2.8 on 2024-01-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_ip_remove_product_views_product_views'),
        ('review', '0004_review_dislike_review_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.product', verbose_name='Продукт'),
        ),
    ]
