# Generated by Django 4.2.8 on 2023-12-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_product_category_id_product_categories'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='market.product', verbose_name='Название'),
        ),
    ]
